name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Version
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1
      - name: Install and Build üîß
        env:
          REACT_APP_CHAIN_ID: ${{ vars.REACT_APP_CHAIN_ID }}
          REACT_APP_COLLECTION_NAME: ${{ vars.REACT_APP_COLLECTION_NAME }}
          REACT_APP_COLLECTION_IMAGE: ${{ vars.REACT_APP_COLLECTION_IMAGE }}
          REACT_APP_COLLECTION_TOKEN: ${{ vars.REACT_APP_COLLECTION_TOKEN }}
          REACT_APP_CURRENCY_TOKEN: ${{ vars.REACT_APP_CURRENCY_TOKEN }}
          REACT_APP_STORAGE_SERVER_URL: ${{ vars.REACT_APP_STORAGE_SERVER_URL }}
          REACT_APP_WALLET_CONNECT_PROJECT_ID: ${{ vars.REACT_APP_WALLET_CONNECT_PROJECT_ID }}
          REACT_APP_RPC_URL_5: ${{ vars.REACT_APP_RPC_URL_5 }}
        run: |
          yarn
          yarn build
      - name: Pages Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
      - name: IPFS Deploy üöÄ
        uses: aquiladev/ipfs-action@master
        with:
          path: ./build
          service: infura
          host: ${{ vars.IPFS_HOST }}
          pin: true
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}
